### ISSUE TITLE
tree ring data folder organization

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#102]
One other little thing I noticed: could you remove the `raw_data` folder highlighted in the image below, and just nest the tree-ring data directly in `tree_rings`? ("Raw data" is misleading, as it's the starting point of your analysis but not the raw data.)
<img width="669" alt="image" src="https://user-images.githubusercontent.com/6355854/145278446-343391dd-c869-4979-aa08-142f55305c05.png">

_Originally posted by @teixeirak in https://github.com/EcoClimLab/growth_phenology/issues/94#issuecomment-989166079_

**Comment by camerondow35** [comment]
Done. Sorry for the delay
