### ISSUE TITLE
Clarify the relationship between stem growth and woody productivity

### ISSUE THREAD

**Issue by camerondow35** [EcoClimLab/growth_phenology#106]
@teixeirak I'm having trouble relating stem growth to woody productivity. Here's what i'm thinking: 

Three cambial processes drive the relationship between stem growth and woody productivity: cell differentiation, cell enlargement, and cell wall thickening. Irreversible stem expansion occurs as a result of differentiation (20% of stem growth) and expansion (80% of stem growth), and accounts for ~10% of annual woody productivity[@cuny_woody_2015]. The remaining 90% of woody productivity is caused by cell wall thickening. It would stand to reason that years with identical stem growth have a similar number of cells which are similarly sized (increased latewood can be an issue here, as  you acknowledge). If we assume that cell wall thickness is controlled by processes within the tree (ie. hormonal responses instead of external climate drivers), then we can predict that cell wall thickness is relatively uniform within each cell type (early wood and late wood). Therefore, years with a similar amount of stem growth would sequester a similar amount of carbon during cell wall thickening, and we can say that stem growth equates to woody productivity. 

But do we know what controls cell wall thickness? (Also, all this info is based on conifers, so it could just be wrong for our trees)

**Comment by teixeirak** [comment]
There's another issue here:

(3) woody productivity is the sum growth of all the trees in the forest. We don't actually calculate this, but rather infer that woody productivity will mirror the growth of the dominant trees. This is a reasonable assumption, and really we care more about how the trees are responding than how these 2 particular forests, with their particular species compositions, are responding. However, technically, we're not calculating woody productivity.

**Comment by teixeirak** [comment]
I'm more concerned about (3) than (2).

**Comment by camerondow35** [comment]
> woody productivity is the sum growth of all the trees in the forest

So we need to make the case that our samples are indicative of the forests they come from? From a not-so-educated point of view, that seems like an easy logical jump for the chronologies. The dendrobands at SCBI also represent a pretty big sample size of the major species, and were spread throughout the plot, so I think that would be fine too. The HF dendrobands might be a little less certain but still seem representative enough for me...

So we could say something like, "Woody productivity is often calculated using a combination of stem growth measurements and forest censuses. By sampling key species across our study plots, we build a dendrometer band dataset that is representative of each species within their respective forests (ie. the response of the overall sample is likely the response of each individual). Because of this, we infer that woody productivity in each forest will mirror the growth of these dominant species. Similarly, tree core chronologies are built using a representative sample of tree cores from each site, so we draw the same conclusions about the correlation between ring width increment and woody productivity of each forest here."

**Comment by teixeirak** [comment]
Let me look at / work oon the wording in the context of the paper. I think we can be pretty brief.

I personally don't feel that it's necessary to prove that our sampled species are exactly representative of these forests, simply because the result we're finding applies to broadleaf deciduous trees in general and should not be dependent upon the particular composition of a patch of forest. If we were trying to quantify the C budget of a particular patch of forest, that would be a different issue.

**Comment by teixeirak** [comment]
Here's a relevant paragraph from Delpierre et al. 2016:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/6355854/155166542-d11ae9e4-d703-4558-a4e7-dca37f8cedf3.png">

**Comment by teixeirak** [comment]
The bottom line is that:
- stem volume growth is usually assumed to equate to woody productivity
- however, this assumption is not fully valid
- existing evidence (including in Delpierre, which I need to cite in this part of the discussion) does not indicate that the extra C in years with warm springs would go into formation of denser wood.

**Comment by teixeirak** [comment]
I think we can close this.
