### ISSUE TITLE
Data cleaning section 

### ISSUE THREAD

**Issue by camerondow35** [EcoClimLab/growth_phenology#108]
A couple reviewers and @teixeirak expressed concern with our data cleaning methods. We ran the dendro band analysis  again using [2.5](https://github.com/EcoClimLab/growth_phenology/tree/2.5SD) and [3 SD](https://github.com/EcoClimLab/growth_phenology/tree/3SD) cutoffs and got the same results. (Links are to branches of main repository, so may not be active forever)

Will update with Response from Neil on logic of removal when he gets back to us.

**Comment by camerondow35** [comment]
*Better to just keep results in an [excel file](https://github.com/EcoClimLab/growth_phenology/blob/master/results/Bayesian%20outputs/cleaning_method_comparison.xlsx)

**Comment by teixeirak** [comment]
@camerondow35 , thanks for loading the [example images of problem fits](https://github.com/EcoClimLab/growth_phenology/commit/69242ba360c7301cdf818313f3d85b6e6d653f9f) (These are also under data/dendrobands/[site]/bad_fits.). I'm flagging @seanmcm here.

**Comment by teixeirak** [comment]
Scrolling through these, it looks like there are a few classes of errors that should be classified as something other than poor fit:

1-  missing early season data. Here's an example where there's no measurement before DOY 150. **Solution: Throw out all data records where the first measurement is missing.**
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/6355854/152683206-d6aa6070-39bc-416f-8cda-934844f71424.png">

2- Large jump after DOY 250.  **Solution: Throw out all data records where there's a jump of greater than `X` from one measurement to the next after DOY 250.** I'm not sure right now what `X` should be, perhaps 20% of total annual growth? 

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/6355854/152683488-19009690-3430-40f5-b276-7babaeb25ebc.png">

3- Very little growth of the tree. **Solution: These should be removed by requiring greater annual growth, as discussed in our recent meeting.**

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/6355854/152683782-771b6821-d1e3-46f6-99f2-209ca44c22ab.png">

4- A few instances where there are clear outliers. 

(This is not all, but all I have time to document right now.)

**Comment by camerondow35** [comment]
Switching to 3 SD lets us include a few really bad model years: 
![image](https://user-images.githubusercontent.com/55721987/152702469-d1ee5d2b-f33d-45f7-bbff-423bd1e02284.png)

@teixeirak if we reduce the number of models removed by the reason stated above, would we lose much by leaving the SD cutoff alone? I'd prefer to leave it at 2 and just report that the results were the same for 2.5 and 3 SD trials. I worry about how many weird models like the two circled above are hiding behind the other data.

**Comment by teixeirak** [comment]
@camerondow35 , I agree that we don't want point like those, which are clearly wrong. Ideally those would be removed by some other criteria before we even consider the 2, 2.5, or 3 SD criteria, and then use 2.5 or 3, but if that's not feasible, then I'd go with 2.5 or 2. Let's hold off on this decision and see where things settle with the new fitting criteria.

**Comment by camerondow35** [comment]
How about removing years where DOY 25, 50, or 75 are ># SD away from the mean for each wood type? I've done a prelim run (1000 iterations instead of 10000) using b and a as end and start DBH and see that we have problems similar to what I posted above.

**Comment by teixeirak** [comment]
That sounds reasonable. If possible, I'd use 2.5 or 3 SD.

**Comment by teixeirak** [comment]
Also, have you tried the filtering procedures that I suggested above?

**Comment by camerondow35** [comment]
Working on them

> 1- missing early season data. Here's an example where there's no measurement before DOY 150. Solution: Throw out all data records where the first measurement is missing.

For this one, the aim would be to remove tag years where we dont capture the beginning of growth, so could we use a date cutoff instead? Ie, remove tag years which first measurements are in May.

**Comment by teixeirak** [comment]
Sure, that works too, and is probably easier to code. I'd use as the cutoff the latest date on which the spring survey was conducted.

**Comment by camerondow35** [comment]
I think we need to use two different definitions of "total growth" in our data cleaning and here's my justification: 

Our definition of total growth in each tree year was incorrect. We previously used L and K from the logistic model, but we actually need to use a and b. A consequence of this change is the overcalculation of `dbh_growth_percent_cummulative` in our data cleaning section. `dbh_growth_percent_cummulative` is calculated by summing up percentage growth cumulatively over the year: 

` dbh_growth_percent = daily_dbh_growth / total_growth,  dbh_growth_percent_cummulative = cumsum(dbh_growth_percent)` .

However, the calculation of daily dbh growth uses modeled dbh, which starts before actual growth (which is counted in a and b) occurs:

 `dbh = lg5(L, K, doy_ip, r, theta, doy), daily_dbh_growth = dbh - lag(dbh) `. 

Since the modeled dbh changes prior to actual stem growth, using `dbh_total_growth = b - a` as the denominator for `dbh_growth_percent` leads to incorrect calculations of ` dbh_growth_percent_cummulative` because max(dbh) does not equal b and min(dbh) does not equal a. Instead, we use `dbh_growth_percent = daily_dbh_growth / (max(dbh)-min(dbh))` for our calculation of daily growth percentages. We can do this because `dbh_growth_percent` and `dbh_growth_percent_cummulative` are only used for removing tree years where modeled growth spiked in unrealistic ways, and not for any further analysis. Because we're looking for spikes in the modeled growth curve, we want a numerator and denominator from the modeled curves in the calculation of `dbh_growth_percent`.

Let me know if this doesn't make sense

**Comment by camerondow35** [comment]
> 1- missing early season data. Here's an example where there's no measurement before DOY 150. Solution: Throw out all data records where the first measurement is missing.

> 2- Large jump after DOY 250. Solution: Throw out all data records where there's a jump of greater than X from one measurement to the next after DOY 250. I'm not sure right now what X should be, perhaps 20% of total annual growth?

I've found that these classes of mistakes only seem to affect the modeled growth outside of a and b, and so they don't cause issues using our new methods. They remove about 150 tree years from each site, but the inclusion of these 150 tree years doesn't appear problematic so i'd recommend not removing them.

**Comment by camerondow35** [comment]
> How about removing years where DOY 25, 50, or 75 are ># SD away from the mean for each wood type? 

We're still getting weird DOY variables with the 3 SD criteria in the DOY timing category. I'd like to switch back to 2 or 2.5 SD. Tags removed at: 
3 SD - HF = 46, SCBI = 27
2.5 SD - HF = 72, SCBI = 51
2 SD - HF = 149, SCBI = 101

**Comment by teixeirak** [comment]
Switching to 2.5 seems fine. I'd only switch to 2 if you can confirm that the bands getting removed are genuinely bad fits.

While you're at it with data filtering, please be sure to remove this terrible outlier (in `pheno_Tsensitivity_combo_patchwork_april.png` but for some reason not `[pheno_Tsensitivity_combo_patchwork_AIC.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/pheno_Tsensitivity_combo_patchwork_AIC.png)`): 
![image](https://user-images.githubusercontent.com/6355854/155133439-02e25b6f-dbe5-4599-aa1d-8385ea9e25ae.png)

**Comment by camerondow35** [comment]
> While you're at it with data filtering, please be sure to remove this terrible outlier

Thankfully that's not an outlier, just a remnant of the old method of calculating total growth! I forgot to switch the data being plotted (sorry Albert....) so it's already taken care of.

**Comment by camerondow35** [comment]
> Switching to 2.5 seems fine.

Committing to a 2.5 SD for all criteria - i'm going back and forth too much so let's just leave everything at 2.5 sd and call it a day.

**Comment by teixeirak** [comment]
Okay, sounds good.

**Comment by teixeirak** [comment]
I think we can close this.
