### ISSUE TITLE
Should we recalculate our DOY% variables using only the growth in b-a?

### ISSUE THREAD

**Issue by camerondow35** [EcoClimLab/growth_phenology#110]
Because of our discussions around using a and b for our total growth, and further explanation of the modeled curves from Sean, i've been rethinking how we calculated our timing variables.

So our current DOY% variables use the modeled lg5 dbh to find 25, 50, and 75% growth. Should we recalculate using only the growth within the a and b variables? Ie, only consider actual growth, not the entire model?

To illustrate, here is a modeled growth curve with the % variables calculated using total modeled growth (blue lines) and % variables calculated using only the modeled change in dbh which falls between a and b (red lines): 

![image](https://user-images.githubusercontent.com/55721987/153507823-d764dde3-9cc9-45ae-be6c-1844ef0c6ff6.png)

The green line represents the final dbh in the previous year, illustrating the point that using our current DOY% variables is incorrect (though, this is an extreme case. When applying this, most change by <10 days). I've already started working on changing them over and a prelim run of the bayesian analysis _hints_ that the results will be slightly different but the conclusion is the same (i'm glad we caught this before any journal accepted it....). This will also involve rerunning the climwin script with the new DOY25's.

**Comment by teixeirak** [comment]
@camerondow35 , I need to understand this better, and hopefully our talk today will clear it up for me, although we might need some input from Sean. 

Are you using data from previous and following years to inform estimation of  `a` and `b`? Sean's paper states that this is possible, although I'd caution that the shrinkage that occurs overwinter is likely to confound this. 

Here's an example image annotated with my current underestimating of the values that might be selected for `a` and `b` if we use (green lines-- paralleling your green line above, at least for `a`) or don't use (blue lines) data from previous and following years:

![image](https://user-images.githubusercontent.com/6355854/153912820-587ea740-5d2f-4a51-9753-257526b45ae8.png)

These could obviously give very different results. I intentionally picked an example with fairly dramatic overwinter shrinkage to illustrate the point, but we'd still expect this to matter.

Based on your comment above, it seems that you're using values illustrated by the green lines, or maybe the green line for `a` and blue line for `b`.  While I think it's valuable to try running it this way, I don't think I trust that, as it cuts off a large portion of the stem expansion phase. Note also that it would bias results of the first and last years, when data from previous and following years (respectively) were not available.

Based on my current understanding, I'd recommend that you:
(1) have the main analysis use `a` and `b` determined independently from one year to the next (i.e., blue lines in the example figure)
(2) mention what results would be if `a` and `b` were informed based on previous and following years (I believe this is the analysis you just tried).
(3) clarify that ∆DBH is NOT net annual growth, but gross annual growth. Retain this as the primary variable of interest.
(4) consider trying to calculate  ∆DBH_net based on corrections relative to previous or following year (one, not both). But note that (a) this would lose a year of data, (b) it could add some mess/ need for additional data screening,  and (c) ∆DBH is not hugely interesting in this analysis, as the tree-ring analysis is far more comprehensive.

**Comment by teixeirak** [comment]
update after our discussion yesterday:

- `a` and `b` were not informed based on previous and following years 
- Thus, the new results correspond to recommendations (1) and (3) above. We will not pursue (2) and (4)

**Comment by teixeirak** [comment]
I think we can close this.
