### ISSUE TITLE
model description error

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#111]
@camerondow35 , I think the statement on line 379 is wrong (xylem porosity not a fixed effect because it was always in separate models): 
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6355854/154960079-0b9eb7e2-34ea-4b45-8bad-11c81009e134.png">

**Comment by camerondow35** [comment]
Xylem porosity is a fixed effect in our models: 

` formula = list(
    DOY_25 ~ wood_type + wood_type:climwinmean + (1 | site) + (1 | tag),
    DOY_50 ~ wood_type + wood_type:climwinmean + (1 | site) + (1 | tag),
    DOY_75 ~ wood_type + wood_type:climwinmean + (1 | site) + (1 | tag)
  )`

So line 380 is incorrect when it says we, "ran separate models for each species group at each site". It should say something like, "We ran separate models for each site"
