### ISSUE TITLE
Harvard Forest 1999

### ISSUE THREAD

**Issue by camerondow35** [EcoClimLab/growth_phenology#114]
@teixeirak FYI, 1999 at Harvard Forest is going to look a bit weird. This was a pretty tough drought year so DOY25 is happening earlier (interestingly, it seems to be impacting DP tree timing more), likely as a consequence of less growth due to drought. This is essentially what Ref 1 was saying about the DOY variables being dependent on one another. I've tried reducing the SD in the DOY timing cleaning category but it doesn't improve much (though, I think we should reduce this to 2 SD which we can discuss in the data cleaning issue).

We already removed 1998 so removing 1999 as well would leave us with 4 years of data for HF. We have two options: 

1.) We can leave it in, explain it, and move on. 
2.) Remove the year 

I think we would be fine leaving it in, but would like your input. 

![image](https://user-images.githubusercontent.com/55721987/154987450-8924de2a-5bf2-4de9-a142-9a6b2d825be3.png)

**Comment by teixeirak** [comment]
I would also favor leaving it in.

**Comment by teixeirak** [comment]
I think we can close this.
