### ISSUE TITLE
papers to read/ cite

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#116]
- [x] Lu & Keenan 2022, GCB: https://onlinelibrary-wiley-com.smithsonian.idm.oclc.org/doi/epdf/10.1111/gcb.16104
- [x] Delpierre 2016 (review)

on C cycle:
- [x] https://www.science.org/doi/10.1126/sciadv.abe9829

 studies that compare TR to flux tower data :

- [x] Belmecheri, S., Maxwell, R. S., Taylor, A. H., Davis, K. J., Freeman, K. H., & Munger, W. J. (2014). Tree-ring δ 13C tracks flux tower ecosystem productivity estimates in a NE temperate forest. Environmental Research Letters, 9(7), 074011. : https://iopscience.iop.org/article/10.1088/1748-9326/9/7/074011
- [x] Rocha, A. V., Goulden, M. L., Dunn, A. L., & Wofsy, S. C. (2006). On linking interannual tree ring variability with observations of whole‐forest CO2 flux. Global Change Biology, 12(8), 1378-1389: https://onlinelibrary-wiley-com.smithsonian.idm.oclc.org/doi/full/10.1111/j.1365-2486.2006.01179.x  - shows decoupling of RWI and eddy flux variables in boreal forest. (Potentially useful citation that I may return to, but not essential.)
- [x] Babst, F., Alexander, M. R., Szejner, P., Bouriaud, O., Klesse, S., Roden, J., ... & Trouet, V. (2014). A tree-ring perspective on the terrestrial carbon cycle. Oecologia, 176(2), 307-322. - good paper, but probably not high enough priority to make the cut
- [ ] also, see refs in delpierre_wood_2016

ITRDB analysis:
- [x] Gao et al: https://www.nature.com/articles/s41559-022-01668-4

early spring and moisture deficits:
- [x] https://www.science.org/doi/10.1126/sciadv.aax0255

**Comment by teixeirak** [comment]
studies that compare TR to flux tower data :

- [ ] Belmecheri, S., Maxwell, R. S., Taylor, A. H., Davis, K. J., Freeman, K. H., & Munger, W. J. (2014). Tree-ring δ 13C tracks flux tower ecosystem productivity estimates in a NE temperate forest. Environmental Research Letters, 9(7), 074011.
- [ ] Rocha, A. V., Goulden, M. L., Dunn, A. L., & Wofsy, S. C. (2006). On linking interannual tree ring variability with observations of whole‐forest CO2 flux. Global Change Biology, 12(8), 1378-1389.
- [ ] Babst, F., Alexander, M. R., Szejner, P., Bouriaud, O., Klesse, S., Roden, J., ... & Trouet, V. (2014). A tree-ring perspective on the terrestrial carbon cycle. Oecologia, 176(2), 307-322.
- [ ] also, see refs in delpierre_wood_2016

**Comment by teixeirak** [comment]
# notes on Gao paper
- ITRDB, so mostly conifers. (We have the larger/more up-to-date data for broadleaf species)
- overall, only 11.4% had sig correlations of RWI with TSOS (need to see if we can dig up stat for eastern US)
- on the surface, their result for eastern US contrasts with ours, but analyses are different (inclusion vs exclusion of conifers, significance thresholds, time frame)

**Comment by camerondow35** [comment]
> on the surface, their result for eastern US contrasts with ours, but analyses are different (inclusion vs exclusion of conifers, significance thresholds, time frame)

On second thought, this seems like it somewhat agrees with our tree core analysis. (If i'm understanding correctly) They found that there weren't many significant increases in stem growth across the eastern US, but there were weak positive responses of tree growth to TSOS across the region. That could mirror what we found, where we see nonsignificant, weak mixed correlations with monthly spring temps for our trees - looking at April Tmax. However, they definitely seem to find more positive interactions than we do, likely because of the differences you listed above.

**Comment by teixeirak** [comment]
I think we're okay on this now. I may return to a couple listed here if needed.
