### ISSUE TITLE
remove DOY_g_max

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#119]
@camerondow35 and I decided to remove DOY_g_max as it's very close to DOY_50, isn't used much, and complicates the story. Here's what needs to go:

- [x] schematic figure (@rudeboybert )
- [x] summary table
- [x] throughout text
- [x] SI table
- [x] elsewhere in SI?

**Comment by rudeboybert** [comment]
done

**Comment by teixeirak** [comment]
Thanks! The figure looks better now that it's less busy.
