### ISSUE TITLE
Suggested changes to EDF2 - growth_curves_all

### ISSUE THREAD

**Issue by camerondow35** [EcoClimLab/growth_phenology#120]
@teixeirak With the new method of calculating total growth, plotting daily growth percentages got complicated. Essentially, daily growth percentage would be 0% until a, then would jump up when a was reached: 

![image](https://user-images.githubusercontent.com/55721987/155851766-70a7092d-c99d-48b1-af6b-31755bc5dc26.png)

This isn't the worst thing in the world, but I figured we could make it look a little better by making some changes. 

Here's what my suggested final product looks like: 

![growth_curves_all](https://user-images.githubusercontent.com/55721987/155851795-a821d5ce-a9c0-47ba-9af1-40f5128559b4.png)

These are averages by year and wood type. Dotted lines represent where growth fell outside of "a" through "b". To calculate where the solid line started, I assigned a marker to all modeled DBH that fell outside of the actual growth (IE, if modeled DBH was < a or > b, rows were assigned a "yes"). Then, I broke these values into two datasets, one with all values < DOY 150 and the other > DOY 150. I then found the median dates with a "yes" (the values which fell outside of a through b) in each dataset. The median DOY from these are where the solid line starts and ends. So the DOY where the solid line starts is the median DOY where "a" was reached in that year, and where the solid line ends is the median DOY where "b" was reached in that year. 

I've also messed around with:

1. averaging values by only wood type, so there's just one line for each wood type. It looks fine, but then we might want to average the leaf pheno data as well. 

2. Adopting the, "DOY's where dbh was outside of "a" through "b" are dotted" method with the original style of plotting each tree year, but it looked really messy and I didn't like it.

**Comment by teixeirak** [comment]
Looks good; let's go with that.

**Comment by camerondow35** [comment]
Ok, pushed the figure and a tentative caption update. Will likely need to keep working on the caption.
