### ISSUE TITLE
QURU & QUAL codes switched in species table

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#121]
@camerondow35 ,

Somehow we got the QURU and QUAL codes switched for SCBI in species_table.csv (so QURU is with Quercus alba and QUAL is with Quercus rubra). This is an easy fix, but we need to make sure we know whether the numbers correspond to the species name or code. Could you please check, keeping in mind that it may be different for the dendrobands and cores?

**Comment by camerondow35** [comment]
Dendroband numbers were switched but cores were fine. I must've originally entered them correctly but mixed them up when I went through this csv after the new data cleaning procedures.

**Comment by teixeirak** [comment]
Thanks! I knit in the fixed table and am closing this.
