### ISSUE TITLE
discussion of differences between SCBI & HF/ 1999 drought

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#122]
@camerondow35 ,

I'm cutting all of the new added text below from the discussion. My reasons are that (1) this is a lot of text, and we need to stay concise and economical with words, (2) we want to keep that first paragraph of the discussion really tight and focused on summarizing how the main results fill our previous gap in understanding, (3) a lot of this content is really results, and is already covered there, and (4) this discussion feels like it's getting too much "into the weeds" (too much detail) for a Nature paper. 

--- 

We find statistically, but not biologically, significant relationships between total growth and spring temperature at both sites in our dendrometer band analysis (`schematic_summary`). 
However, the slope of the relationships are in opposite directions, with warming causing decreasing stem growth at Harvard Forest but increasing stem growth at SCBI (`EDT_phenology_parameters`). 
We believe this difference is due to severe drought conditions in 1999 which obviously caused abnormal growth patterns in that year (`r EDF_pheno_Tmax_climwin`). 
Therefore, we suggest that our two sites represent two scenarios: 1. A forest which had no significant summer drought, but was only influenced by warming temperatures (SCBI). 2. A forest which experienced spring warming along with severe summer drought (Harvard Forest).

At SCBI, we see a very small increase in total stem growth (on average +0.05mm/$^\circ$C), suggesting that even in the absence of drought or inclement climate conditions during the growing season, spring warming does not enhance stem growth in a meaningful way.
At Harvard Forest, we see a decrease in total growth with warmer temperatures in the CTW (-0.15mm/$^\circ$C on average). We speculate that this result is likely a product of reductions in total stem growth related to drought effects in 1999. 
Due to the method of selection for CTW, years with significant departures from the norm can influence the analysis to a greater extent. 
Stem growth in 1999 was clearly impacted by climate conditions (`r EDF_pheno_Tmax_climwin`), and so the CTW selected by climwin maximizes the effect of these impacts (most likely the effects of drought) on stem growth. 
To examine this further, we reran our dendrometer band analysis using the month of May as the CTW. 
When we change the CTW to the month of May, we see results much closer to those found at SCBI, with a similar advancement in growth timing but a much less pronounced effect of $T_{max}$ on total growth (-0.015mm/$^\circ$C on average, a tenfold decrease compared to the CTW optimized around the drought year;`EDF_pheno_Tmax_AprilMay`). 
Once again see that there was no meaningful influence of spring temperature on total growth. 
In fact, the magnitude of the effect of the summer drought compared to the effects of spring $T_{max}$ illustrates the point that conditions during the peak growing season are much more influential to stem growth than conditions during the Spring.

**Comment by teixeirak** [comment]
We will want to make sure we capture anything that's unique and important elsewhere, which is why I'm opening this issue.

**Comment by camerondow35** [comment]
> On a related note, we say "However, we did not find evidence that higher spring temperatures were correlated with summer drought stress in our dendrometer band analysis, implying that the effects of warm spring temperatures on stem growth elucidated here (Fig. r schematic_summary) were not attributable to summer drought." This is detailed in the methods. But this seems to contradict the removed text above. @camerondow35 , did you redo that analysis? Or is this text old?

I suppose it's worded weird and I definitely should've updated it, sorry. 

> "However, we did not find evidence that higher spring temperatures were correlated with summer drought stress in our dendrometer band analysis, implying that the effects of warm spring temperatures on stem growth elucidated here (Fig. r schematic_summary) were not attributable to summer drought."

This statement refers to the average effect of spring temps on summer SPEI. We found no significant effect, and so we say that on average, the spring temps weren't causing more drought. If you look at our SPEI plots we see that 1999 there was a potential relationship, but every other year reduces the impact of 1999 on the overall analysis: 
![image](https://user-images.githubusercontent.com/55721987/157509996-259d800f-9262-4c53-9c0f-5c39ba73f6dc.png)

How about: "We did not find evidence that higher spring temperatures were correlated with summer drought stress in our dendrometer band analysis, implying that warmer spring temperatures were acting independent of summer drought in most years of our analysis. However, we see a clear effect of summer drought at Harvard Forest in 1999 which reduced growth in that year."

**Comment by camerondow35** [comment]
As for removing all of that text, we need to include some discussion explaining the differences somewhere. Maybe Including it around the discussion of SPEI? I think including it in the statement I suggested above might work. I think it deserves a good amount of attention in the discussion, but if you think it's less important that's fine.

**Comment by teixeirak** [comment]
I still question whether it deserves so much attention. It's one anomalous year at one site, and while it does affect the slopes of relationships, it doesn't fundamentally change the story. In a paper this concise, there's really not much space to get into side-stories.

Also, I'm wondering how anomalous 1999 really was. Do you have additional sources documenting this as a year of significant drought besides SPEI? A SPEI of ~ -1 is drier than average, but based on my understanding of the metric and the [SPEI website](https://spei.csic.es/), it doesn't seem to qualify as a very rare or extreme drought. Looking at your full plots (below), there was a year at SCBI that was almost as dry.  

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/6355854/157515111-69b939f1-2dc6-4418-8190-6ef2c57d3655.png">


Neil talks about how HF hasn't had any really meaningful drought in decades...

**Comment by camerondow35** [comment]
I guess I took Loic's word for it: 

"On-site weather records indicate that the study period included the driest summer (1999) over a 26-year period (1991–2017), with monthly precipitations of 52 mm relative to a monthly average of 111 mm from June to August. The last two decades, however, represent a regional wet period with increased frequency of rainfall events during the summer ([Bishop and Pederson 2015]."

**Comment by camerondow35** [comment]
Knowing that ^ and seeing how 1999 was a very anomalous year, I just put 2 and 2 together.

**Comment by camerondow35** [comment]
Anomalous in terms of growth patterns*. If you look at the pheno_tsensetivity figure it stands out alot, and needs to be explained. 

![image](https://user-images.githubusercontent.com/55721987/157517190-82cd5b93-a8bb-4a42-b9fe-039193899d91.png)

**Comment by teixeirak** [comment]
I definitely wouldn't deny that it's the driest, but that doesn't necessarily make it a strong drought, especially given the trend toward increasing rainfall at the site. Defining and quantifying drought is always tricky-- there are many different definitions and time scales, and then the question of if/how it's biologically relevant. (And we do see that year as anomalous, so worth mentioning, but not sure it justifies being highlighted/ discussed.)

**Comment by teixeirak** [comment]
> Anomalous in terms of growth patterns*. If you look at the pheno_tsensetivity figure it stands out alot, and needs to be explained.
> 
> ![image](https://user-images.githubusercontent.com/55721987/157517190-82cd5b93-a8bb-4a42-b9fe-039193899d91.png)

1999 is the year on the far right of these plots, correct?

**Comment by camerondow35** [comment]
> 1999 is the year on the far right of these plots, correct?

Yep!

**Comment by camerondow35** [comment]
> (And we do see that year as anomalous, so worth mentioning, but not sure it justifies being highlighted/ discussed.)

I think it also highlights a weakness of our analysis, which is worth discussing too. It's a good launching point into the monthly tmax ctw's instead of the climwin derived ctw's

**Comment by teixeirak** [comment]
I think it's good to mention this (at least in theory). We obviously wouldn't want to hide it, but I also don't think it clears the (high) bar for discussion of more than 1-2 sentences in the main manuscript (if that). It's one anomalous year, but I don't think it would qualify as enough of a drought that one would want to claim it as a good example for understanding drought responses. The fact that we have such a limited sample size (1 drier year, 4 "normal") makes me uncomfortable in using this to try to draw broad conclusions.

**Comment by teixeirak** [comment]
I believe you meant April, not May, in this statement: "To examine this further, we reran our dendrometer band analysis using the month of May as the CTW." Correct? (You're talking about the analysis in Extended Data Fig. 5, which is all April, right?)

**Comment by teixeirak** [comment]
> > (And we do see that year as anomalous, so worth mentioning, but not sure it justifies being highlighted/ discussed.)
> 
> I think it also highlights a weakness of our analysis, which is worth discussing too. It's a good launching point into the monthly tmax ctw's instead of the climwin derived ctw's

Agree, BUT... The discussion of a Nature (or short format) paper needs to be really concise and stick to the most essential points. While the results are somewhat influenced by this anomalous year, it does not affect our **conclusions**. Similarly, we have somewhat different results but the same conclusions regardless of how we select the CTW.

**Comment by camerondow35** [comment]
>  (You're talking about the analysis in Extended Data Fig. 5, which is all April, right?)

It was always May for HF from what I remember, but we get similar results for April tmax. EDF5 is all May now, because SCBI DOY25 was weird for April tmax. 

I was planning on creating an official version of that "comparison table" for the SI. In it i'd like to have bayesian results for climwin, april, and may CTW's. Would you be fine with that?

**Comment by camerondow35** [comment]
> While the results are somewhat influenced by this anomalous year, it does not affect our conclusions.

Ok, I think adding 1-2 sentences and the suggested SI comparison table could be enough.

**Comment by teixeirak** [comment]
> > (You're talking about the analysis in Extended Data Fig. 5, which is all April, right?)
> 
> It was always May for HF from what I remember, but we get similar results for April tmax. EDF5 is all May now, because SCBI DOY25 was weird for April tmax.
> 
> I was planning on creating an official version of that "comparison table" for the SI. In it i'd like to have bayesian results for climwin, april, and may CTW's. Would you be fine with that?

I don't think we have space-- we'd have to sacrifice some other display item, as we're at the 10 max.

**Comment by camerondow35** [comment]
We do need to acknowledge that for whatever reason, 1999 had the lowest total growth. While it might not have been a major drought, it seemed to have some effect.

 Year  Total Growth
 1999 0.1897616
 2000 0.2013485
 2001 0.2173154
 2002 0.2168089
 2003 0.2024734

**Comment by teixeirak** [comment]
> It was always May for HF from what I remember, but we get similar results for April tmax. EDF5 is all May now, because SCBI DOY25 was weird for April tmax.

We had all April in the submitted version: https://github.com/EcoClimLab/growth_phenology/issues/82.

**Comment by teixeirak** [comment]
Are you able to shift this conversation to Teams? The back-and-forth on GitHub issues is tough.

**Comment by teixeirak** [comment]
> We do need to acknowledge that for whatever reason, 1999 had the lowest total growth. While it might not have been a major drought, it seemed to have some effect.
> 
> Year Total Growth 1999 0.1897616 2000 0.2013485 2001 0.2173154 2002 0.2168089 2003 0.2024734

So 1999 growth is 87% that of highest year (2001) and 94% that of 2nd-lowest year (2000). While lower and something we can mention if space permits, I still wouldn't make a big deal of it.

**Comment by teixeirak** [comment]
Since we're already over length, we don't have space to discuss this. (I wouldn't prioritize it over current content.) So closing.
