### ISSUE TITLE
provide more context on climate during study period

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#127]
@camerondow35 , I added placeholders in the methods section to provide some context on the climate during our study periods. What I had in mind was to present something on how drought (SPEI) relates to the longer-term climate (30+ years). It would also be good to do this for temperature, and spring temperatures in particular. We obviously won't want to get too complex, just enough to give a sense of how our study period compares to normal. 

Note that we currently have a statement in the discussion claiming "relatively mesic conditions". I wrote this with the assumption that 1999 was not a terribly strong drought at HF, and also that 2012 (drought year) was not terribly anomalous at SCBI. We'll need to modify this statement if either of these turns out to be highly unusual relative to the mean climate.

**Comment by teixeirak** [comment]
(Either one of us could do this-- just whoever gets to it first. I'm swamped right now, so it would help if you could get to it, but I'll do it if I get time for it first.)

**Comment by camerondow35** [comment]
For spring temps, should I just use April? Or some combination of months? I was thinking March + April at least.

**Comment by teixeirak** [comment]
It depends on exactly what you want to do (I think there's a lot of room for flexibility here). The simplest would be to focus on April temperatures. I think this is justified in that April is the middle and most common month within the range that comes out in the climwin analysis (March-May).

**Comment by camerondow35** [comment]
I was thinking March + April just to be sure that we capture the earliest warming that could impact growth. No matter what, it's looking like both sites are consistently warmer and wetter in the study period so what we choose doesn't really matter.

**Comment by teixeirak** [comment]
Okay. Do what makes most sense to you. The main point is to give some context on how the climatic conditions during our study period compare to normal.

**Comment by teixeirak** [comment]
@camerondow35 , I've done what I could on the first 2 points above. There are a some numbers/ items for you to fill in (in bold).

**Comment by teixeirak** [comment]
Thanks for adding those stats! Good improvement. I'll tweak a few things.
