### ISSUE TITLE
use consistent units on gmax and ∆DBH

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#128]
We need to standardize units (mm vs cm) on g_max and ∆DBH throughout. This pertains to extended data table 2 (listed in mm), extended data figs 4-5 (listed as cm), and possibly other places.

**Comment by teixeirak** [comment]
@camerondow35 , flagging you here to make sure you see this.

**Comment by camerondow35** [comment]
EDF4 would take the most work to change so it's easiest if we use cm everywhere.

**Comment by teixeirak** [comment]
Thanks!
