### ISSUE TITLE
details

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#129]
Here's a running list of small things that need to be finished

- [x] fill in placeholders for refs (@teixeirak )
- [x] eliminate some references (#125 ; @teixeirak )
- [x] quilt plot methods paragraph needs some attention from @camerondow35 and dendro coauthors

**Comment by camerondow35** [comment]
> quilt plot methods paragraph needs some attention from @camerondow35 and dendro coauthors

I answered the comments in the quiltplot method paragraph in my latest commit.
