### ISSUE TITLE
editorial comments

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#137]
I believe the specific comments here are all we really need to pay attention to-- general point there just for reference.

# Some specific comments:

- [x] Please reduce the article title to 75 characters (with spaces) or less. #139 
- [x]  Please reduce the main text references to 50 in total or less - currently there are 80. *(This is just because we have the methods references in the wrong place. I don't think .Rmd can be programmed to do this right, so just need to change manually at the end.)*
- [x] #143
- [x] There are no methods references - please create a separate reference list for the methods with continuous numbering. *(This is just because we have the methods references in the wrong place. I don't think .Rmd can be programmed to do this right, so just need to change manually at the end.)*
- [x] Please remove the main figures from the article file and re-supply them individually in an acceptable format such as EPS, AI, PS, PDF, PPT, CDR, PSD or XLS (for graphs).
- [x] Please provide the Extended data figures in EPS, JPEG or TIF format.
- [x] Figure 3 is too tall in height when re-sized to 18 cm width, please reduce to 17 cm or less.
- [x] #144
- [x] Please let us know the sources of the map illustrations in extended data figures.
- [ ] #146
- [x]  Please provide a competing interest statement.
- [x]  In the ‘Data presentation’ section of the EPC, you have marked ‘N/A’ in the field corresponding to data distribution format; however, that field seems relevant to the study.
- [x]  In the ‘Data presentation section of the EPC, you have marked the field confirming clearly defined error bars are present as ‘N/A’; however, there are error bars in the supplementary figures.

# More general points:

LENGTH: The length for the summary paragraph and body text should not exceed 2500-3000 words, and up to 4 ‘modest’ display items; a modest display item is one that, with its legend, occupies about a quarter of a page (equivalent to ~270 words). If a composite figure (with several panels) needs to occupy at least half a page in order for all elements to be visible, the text length may need to be reduced accordingly to accommodate such figures. Essential but technical details can be moved into the Methods or Supplementary Information (see below).

TITLE: Titles cannot exceed 75 characters (including spaces); they must not contain punctuation.

SUMMARY PARAGRAPH: Papers start with a fully referenced, bold paragraph, ideally of about 200 words, aimed at readers in other disciplines. Numbers, abbreviations, acronyms or measurements should be avoided unless essential. The summary paragraph consists of 2 to 3 sentences of basic-level introduction to the field; a brief account of the background and rationale of the work; a statement of the main conclusions (introduced by the phrase 'Here we show' or its equivalent); and a conclusion of 2 to 3 sentences putting the main findings into general context so it is clear how the results described in the paper have moved the field forward. A downloadable, annotated example is available at [https://www.nature.com/nature/for-authors/formatting-guide.](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature%2Ffor-authors%2Fformatting-guide.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3tohZXnIDj9%2BHlW258tPIwLWLBfk2vAItqawsp4bODM%3D&reserved=0) 

MAIN TEXT: If further introductory material is necessary, the main text can begin with up to 500 words of introduction expanding on the background to the work (some overlap with the summary is acceptable), before proceeding to a concise, focused account of the findings, and ending with 1 or 2 short paragraphs of discussion. Sections are separated with subheadings (up to 40 characters including spaces) to aid navigation. 

REFERENCES: As a guideline, most papers should include no more than 50 main text references; all additional references can be cited in (and listed after) the Methods section, as detailed below.

FIGURE LEGENDS: These should be listed sequentially after the main text references and not in the figure files. Each legend should begin with a brief title for the whole figure and continue with a short description of each panel and the symbols used. Legends should not exceed 300 words each. Each figure legend should contain, for each panel where relevant, the following information:
* the exact sample size (n) for each experimental group/condition, given as a number, not a range;
* a description of the sample collection allowing the reader to understand whether the samples represent technical or biological replicates (including how many animals, litters, cultures, etc);
* a statement of how many times the experiment shown was replicated;
* definitions of statistical methods and measures:
* very common tests (e.g. t-test, simple Chi-square tests, Wilcoxon and Mann-Whitney tests) can be identified by name only, but more complex techniques should be described in the Methods;
* whether tests are one-sided or two-sided;
* whether there are adjustments for multiple comparisons;
* the statistical test results (e.g., P values);
* the definition of ‘center values’ as median or average;
* the definition of error bars as s.d. or s.e.m.
Descriptions that are too long for the figure legend should be included in the Methods section; see [https://www.nature.com/nature/for-authors/formatting-guide](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature%2Ffor-authors%2Fformatting-guide&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G%2BrRLMDfsudL4K%2BbvXkBgVsK04X0dPGVE74gbRZuEf0%3D&reserved=0) for further explanation.

METHODS: The Methods section, which provides the full, step-by-step instructions that would allow other researchers to replicate the results, is included after the main text figure legends. The Methods section will not appear in print but will appear online in the full-text HTML and PDF versions. The Methods section should be written as concisely as possible but should contain all elements necessary to allow interpretation and reproduction of the results. If there are additional references (in the Methods section, Supplementary Information, etc), their numbering should continue from the last entry in the main text reference list, and they should be listed following the Methods section. Specialized methods that require chemical structures, figures or tables, or methods requiring equations, cannot be accommodated in the Methods section of the main text file. If such information is part of the Methods, the entire Methods section must instead be included within a Supplementary
Information text file.

MAIN TEXT STATEMENTS: Several statements (which will not appear in print but will appear online in the full-text HTML and PDF) are required after the Methods (and additional references, if present). First, there should be an Acknowledgements section, listing grant/financial support. Next, we require a detailed Author Contribution statement; the specific contributions of each author, particularly in terms of which authors performed which specific experiments, must be listed. This is followed by a Competing Interest statement. Financial and non-financial interests should be noted here, as well as any patents; patent information should include at a minimum what is covered by the patent and who submitted the patent application. Finally, an Additional Information statement should include information regarding reprints and permissions and name the author(s) to whom correspondence and requests for materials should be addressed. For formatting details and an example see
[https://www.nature.com/nature/for-authors/formatting-guide.](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature%2Ffor-authors%2Fformatting-guide.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3tohZXnIDj9%2BHlW258tPIwLWLBfk2vAItqawsp4bODM%3D&reserved=0)

DATA AND CODE AVAILABILITY STATEMENTS: All published manuscripts reporting original research in Nature Portfolio journals must include a data availability statement. The data availability statement must make the conditions of access to the “minimum dataset” that are necessary to interpret, verify and extend the research in the article, transparent to readers. This minimum dataset may be provided through deposition in public community/discipline-specific repositories, custom proprietary repositories for certain types of datasets, or general repositories like Figshare, Zenodo and Dryad. Providing large datasets in supplementary information is strongly discouraged and the preferred approach is to make data available in repositories. More information on Nature Portfolio’s reporting standards and preparing your Data Availability Statement can be found here: [https://www.nature.com/nature-portfolio/editorial-policies/reporting-standards](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature-portfolio%2Feditorial-policies%2Freporting-standards&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I3uIDdDCczzYE5zjZHhD5mRRbcy9y9OqQHAHrHCkSoM%3D&reserved=0)#reporting-requirements 

For all studies using custom code or mathematical algorithm that is deemed central to the conclusions, a statement must be included under the heading "Code availability", indicating whether and how the code or algorithm can be accessed, including any restrictions to access. Code availability statements should be provided as a separate section after the data availability statement but before the References. Code should be deposited in a DOI-minting repository such as Zenodo, Gigantum or Code Ocean and cited in the reference list. Authors are encouraged to manage subsequent code versions and to use a license approved by the open source initiative. Additional details can be found here: [https://www.nature.com/nature-research/editorial-policies/reporting-standards](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature-research%2Feditorial-policies%2Freporting-standards&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eyqD3yXbb%2BIdqevAnSHMyWBmoh5QZL5qawEKg5ycv9I%3D&reserved=0)#availability-of-computer-code. 

DISPLAY ITEMS: We suggest that you take stock of all data that have been generated throughout the review process and ensure that only the data most central to the conclusions are presented in the main text figures. Any figures included within the main text file during the review process must be removed from the final main text file and uploaded as separate, individual files; they will be integrated into the main paper in print and online. An overview of the key features of this presentation may be found at [http://s3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com/uploads/ckeditor/attachments/7824/3g_Paper_composition.pdf.](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fs3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com%2Fuploads%2Fckeditor%2Fattachments%2F7824%2F3g_Paper_composition.pdf.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kaKH6Z4Fos7p5s7uE%2F3uRReG8n4Q%2FKjbh1c45ISyYjE%3D&reserved=0)

Figures should be comprehensible to readers in other disciplines and assist in understanding of the paper. Main text figures (but not Extended Data) must be provided in production-quality versions in an editable format (i.e., .ai, .cmx, .cdr, .doc, .eps, .pdf, .ppt, .ps, .psd, .svg and .xls); we cannot accept figures in .cvs, .gif, .jpg, .png and .tif formats. We strongly encourage you to consult the guidelines at [http://s3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com/uploads/ckeditor/attachments/7822/3c_Final_artwork.pdf.](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fs3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com%2Fuploads%2Fckeditor%2Fattachments%2F7822%2F3c_Final_artwork.pdf.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SS2EOTWPC9PmCwVxL%2FqVINkeHybPvdjQp54DaJ4BGyo%3D&reserved=0) They should be as small and simple as is compatible with clarity. All panels of a figure should be logically connected and assembled on a single page in a rectangular shape; any essential alignments (parts horizontal, vertical, spacings of stereo pairs, etc) should be indicated. Each panel of a multipart figure should be sized so that the whole figure can be proportionally reduced and reproduced on the printed page at the
smallest size at which essential details are visible. Nature's standard figure sizes are either 9 or 18 cm wide; the maximum permitted height is 17 cm. You should arrange the panels to fit these widths while minimizing excess space around the panels. Tables should be prepared using the Table menu in Microsoft Word. As we must be able to edit the figures so that they conform to our house style, the submission of files that are incorrectly formatted, flattened, or of insufficient resolution may delay final acceptance of your manuscript. Any images, illustrations, etc that are reused must be identified so that the appropriate permission can be obtained and credit can be given.

IMAGE INTEGRITY: We strongly advise that you go carefully through all the data (including Extended Data and Supplementary Information) to ensure there are no accidental image/data duplications, other image manipulations or data errors. Such issues generally require correction after publication. Any image provided for publication, either in print or online (including Extended Data and Supplemental Information), may be subject to a quality control process to check for image integrity and manipulation. A discussion of our standards regarding how images should be prepared and presented can be found at [https://www.nature.com/authors/editorial_policies/image.html.](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fauthors%2Feditorial_policies%2Fimage.html.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9Vk4YLQNZkgLidFTn%2F%2F6nMmAuS3V9lnk8bSSs93LFVs%3D&reserved=0)

EXTENDED DATA: Extended Data do not appear in print but are included online within the full-text HTML and integrated in the downloadable PDF. Extended Data are an integral part of the paper, and only data that directly contribute to the main message should be included. All Extended Data must be referred to in the main text, and their legends should be listed sequentially at the end of the main text, not in the Extended Data files. Extended Data should be assembled into a maximum of 10 A4 size, multi-panelled display items. They must be supplied as individual files in .jpg, .tif or .eps format only. They should be of the same quality as the main figures, but there are important differences in their formatting. More specific instructions are provided here: [http://s3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com/uploads/ckeditor/attachments/7823/3h_Extended_data.pdf.](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fs3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com%2Fuploads%2Fckeditor%2Fattachments%2F7823%2F3h_Extended_data.pdf.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E9akmVUHSBtyNniy1lz%2BCxY7RiqpIzrzgRlshcn9i5Q%3D&reserved=0) We encourage authors who are describing complex processes to include a schematic of
the main finding as part of the Extended Data to aid readers unfamiliar with the immediate discipline.

SUPPLEMENTARY INFORMATION: Supplementary Information (SI) is online-only, peer-reviewed material that is essential background to the study (e.g., large data sets, more complex methods, and calculations), but which is too large or impractical, or of interest only to a few specialists, to justify inclusion in the print version of the paper (see [https://www.nature.com/nature/for-authors/supp-info](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature%2Ffor-authors%2Fsupp-info&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7yIdVCecAdD%2FSrP94jsEZvk6DdhjnRs64SfODFaxUbU%3D&reserved=0) for further details). While SI should not typically contain data figures (any figures additional to those appearing in the main text should be formatted as Extended Data), we require that the raw, uncropped data for gels be presented as an SI figure (see below). Tables may be included in SI, but only if they are unsuitable for formatting as Extended Data (e.g., tables containing large data sets or raw data tables that are best suited to Excel files). If a manuscript has SI, each discrete item of the SI (e.g., videos, tables) must be referred to at an appropriate point in the main manuscript.
We ask that you provide a word file entitled “SI Guide”, containing a cover page with manuscript title and author information; a table of contents (preferably with page numbers); and then any SI text, notes, figures, and titles and legends for any separate SI files. Additional information can be found at [https://www.nature.com/nature/for-authors/supp-info.](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature%2Ffor-authors%2Fsupp-info.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tRvTE9aLykLXyoirbXsWxohxsCbKSTtnQ69Qox00aV8%3D&reserved=0)

Please pay careful attention to the formatting of the SI because it is not subedited. After the paper has been accepted, SI files can only be amended for critical changes to the scientific content, not for style.

SOURCE DATA (GRAPHS): To increase transparency, we strongly encourage you to provide, in spreadsheet form, the data underlying the graphical representations used in figures. In the case of all experiments presenting data from animal models, this is a requirement and is not optional. This is in addition to our well-established data-deposition policy for specific types of experiments and large datasets. Online readers of the manuscript will be able to access the graphical source data directly from the figure legend. Spreadsheets must be submitted in .xls, .xlsx or .csv formats. One file per figure is permitted. If there is a multi-panelled figure, the source data for each panel should be clearly labeled in the file; alternatively the source data for a figure can be included in multiple, clearly labeled sheets within an Excel file. File sizes of up to 30 MB are permitted, but it is expected that the vast majority of graphical source data files will be considerably smaller than this.
When submitting these files with your manuscript, you should select the "Source Data" file type and use the title field in the file description tab to indicate the figure(s) to which the source data pertain. Source data should not be provided as Extended Data.

DATA DEPOSITION: The following specific points may be relevant to your paper, so please ensure that you provide the following information:

* Sequences for any RNAi/small RNA constructs must be included.

* Accession numbers for gene expression data or RNA sequencing data must be listed.

* Papers reporting protein structures must conform to our standards listed in the Guide to Authors ([https://www.nature.com/authors/editorial_policies/availability.html](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fauthors%2Feditorial_policies%2Favailability.html&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mJnzl6VNyaGOJzR4E18FeMa8FBFHOdId59oBbf%2FPuPk%3D&reserved=0)). The DAS must state that the X-ray crystallographic coordinates and structure factor files (or comparable NMR or cryoEM data) have been deposited in the appropriate, named, public database, along with all relevant accession number(s). You must use the standard Nature templates for structural data ([https://www.nature.com/nature/for-authors/formatting-guide;](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fnature%2Ffor-authors%2Fformatting-guide%3B&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269556559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qDwdCYdFxhWtzyOysNRjtfVG2Gy9%2BsmM8cNvzvMpKDQ%3D&reserved=0) this url contains separate links to tables for X-ray crystal, NMR and cryoEM structures). These tables should be presented as Extended Data. The contour level of any electron density maps presented, as well as the type of map (i.e., Fo-Fc or 2Fo-Fc), should be explicitly stated in the figure legend. 

* For every new chemical compound, a complete description of the synthesis and the physical characterization (i.e., NMR, MS, etc) must be included in the Supplementary Information (see [https://www.nature.com/documents/nature-chemical-characterization-guidelines.pdf](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fdocuments%2Fnature-chemical-characterization-guidelines.pdf&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269712790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Nm59v%2Fd0EsDuxzNcus2D8YKWBL%2F7BOfXK583lMfrrA4%3D&reserved=0)).

* Papers containing new or revised formal taxonomic nomenclature for animals, whether living or extinct, are accepted conditional on the provision of LSIDs (Life Science Identifiers) by means of registration of such nomenclature with ZooBank, the online registration system for the International Code of Zoological Nomenclature (ICZN). ZooBank LSIDs can be resolved and the associated information viewed through any standard web browser by appending the LSID to the prefix "[http://zoobank.org/](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fzoobank.org%2F&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269712790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xG2%2Ba5%2FptYP8fjVmK5P5K6DeRLALyCzfva04ny9bqXE%3D&reserved=0)".

* We strongly encourage deposition of 3D morphological data in a suitable repository such as MorphoBank, MorphoSource or similar; the relevant accession numbers should be listed in the DAS.

* For animal experiments, you must confirm that all experiments were performed in accordance with relevant guidelines and regulations. There should be a statement identifying the institutional and/or licensing committee approving the experiments, including any relevant details. Sex and other characteristics of animals that may influence the results must be described. Details of housing and husbandry must be included if they are likely to influence experimental results. Further details can be found at [https://www.nature.com/authors/policies/experimental.html.](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fauthors%2Fpolicies%2Fexperimental.html.&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269712790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ad1YOILo%2FSOVccb%2BZfQsT7qiuzdZypddTPgo1J%2FZB6o%3D&reserved=0)

* Human genotype data (e.g., SNP array data) should be deposited into a public database (dbGAP or EGA) with controlled access policy for human genotype data.

* A full clinical and pathological characterization of patients/human subjects and samples should be provided in tabular format, including the magnitude of response for each patient (partial, complete, stable disease), the site of the biopsy, whether or not that lesion was progressing, and mutational status if appropriate.

CONSORTIA: For papers containing one or more consortia, all members of the consortium who contributed to the paper must be listed in the paper (i.e., print/online PDF). If necessary, individual authors can be listed in both the main author list and as a member of a consortium listed at the end of the paper. When submitting your revised manuscript via the online submission system, the consortium name should be entered as an author, together with the contact details of a nominated consortium representative. See [https://www.nature.com/authors/policies/authorship.html](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fauthors%2Fpolicies%2Fauthorship.html&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269712790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kQIdjuKyw85pYhZhpS5w0Rgtys4WUWevMnJ8oE3TDUk%3D&reserved=0) for our authorship policy and [https://www.nature.com/documents/nr-consortia-formatting.pdf](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fdocuments%2Fnr-consortia-formatting.pdf&data=05%7C01%7CTeixeiraK%40si.edu%7C3361e6acf42149697aab08da24772107%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637862392269712790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7IhYza4AQKk0UWcDTWXUNcyyoHK%2F8RjxTYZz%2B%2FxCw9w%3D&reserved=0) for further consortia formatting guidelines, which should be adhered to prior to acceptance.

**Comment by camerondow35** [comment]
> Please ensure that the text size in all figures is at least 5 pt Arial.

Do you know how to change the font in an rmd table? I've tried changing font in the csv and adding `mainfont = Arial` / `\fontspec{Arial}` to the extended data rmd but neither seemed to work. It seems like the tables are the issue here. 

> Please let us know the sources of the map illustrations in extended data figures.

This is in reference to EFD1? That map is from ggplot2. 

> Figure 3 is too tall in height when re-sized to 18 cm width, please reduce to 17 cm or less.

Are they asking us to change the height to 17cm while the width will be 18cm?  That would make the figure into a weird square...

**Comment by teixeirak** [comment]
> > Figure 3 is too tall in height when re-sized to 18 cm width, please reduce to 17 cm or less.
> 
> Are they asking us to change the height to 17cm while the width will be 18cm? That would make the figure into a weird square...

It sounds like that. It sure will crunch it down into an almost impossible size... Perhaps we should check with the editor? But I do think that's what's meant.

**Comment by camerondow35** [comment]
> Which looks suspicious to you? Presumably EDT3 (smallest font size of all)?

I think the font in all the tables needs to be changed

**Comment by teixeirak** [comment]
Are you sure? The checklist says figures, not tables. To me it looks like the smallest fonts anywhere are the axis labels on EDF 3, probably followed by the index numbers on the 3 tree-ring plots. (Tables EDT1 and EDT2 have fonts bigger than the captions.)

**Comment by camerondow35** [comment]
> Are you sure? 

It seems weird to have different font types for tables and figures, but you're right, they just mention figures. 

> the index numbers on the 3 tree-ring plots

These should be large enough in the original images, may become too small because of the way we screenshot the final figure.

**Comment by teixeirak** [comment]
Oh no, I'm sorry... This whole time I've been thinking about font size, thinking you wanted me to make the table font bigger! That's just because I didn't read well. I'll look at this in the morning.

**Comment by teixeirak** [comment]
> > > Please ensure that the text size in all figures is at least 5 pt Arial.
> > 
> > 
> > Do you know how to change the font in an rmd table? I've tried changing font in the csv and adding `mainfont = Arial` / `\fontspec{Arial}` to the extended data rmd but neither seemed to work. It seems like the tables are the issue here.
> 
> Which looks suspicious to you? Presumably EDT3 (smallest font size of all)? I think that still looks bigger than some of the figures. Perhaps some of the font is getting smaller than programmed when the figure is shrunk to size? (Font and figure sizes can sure be annoying...)

@camerondow35 , Are you sure that changing the font to Ariel is necessary? It looks like it's a tricky thing to do, so I'd rather not bother unless it's specifically requested. Are you basing this on the request "Please ensure that the text size in all figures is at least 5 pt Arial."? If so, I'd think that applies to the figures, and I wouldn't worry about the tables. They can always come back to us if this is a problem.

**Comment by camerondow35** [comment]
> Are you sure that changing the font to Ariel is necessary?

I'm not sure. So we can leave it alone for now.

**Comment by camerondow35** [comment]
>  Figure 3 is too tall in height when re-sized to 18 cm width, please reduce to 17 cm or less.

See [the commit I made a few days ago](https://github.com/EcoClimLab/growth_phenology/commit/9f686f4e45d0e0c9ff80157ad71033c9b588a9b0) which I think solves this. I just resized it in powerpoint then saved the image manually (no screenshot)

>  Please supply Table 2b in the article file in an editable format. Does this refer to table in Figure 1b?

I guess. We have this already but the text is latex based, right? Is that a problem?

**Comment by camerondow35** [comment]
> Please ensure that the text size in all figures is at least 5 pt Arial. which don't meet this standard?

I think this is ok?

**Comment by teixeirak** [comment]
We have completed all but the SI guide, which is now it's own issue, so closing this.
