### ISSUE TITLE
take & select potential cover images

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#140]
From email: 

*If you wish, you may also upload up to six high resolution images as potential cover illustrations. The file name should include the manuscript reference number and be labelled as a cover suggestion; a short description is also preferred. Illustrations should be selected more for their aesthetic appeal than for their scientific content. We cannot promise that your suggestions will be selected for the cover, as competition is intense.*

**Comment by teixeirak** [comment]
I took some potential photos last week, but plan to go back next week in the hopes of getting something better. I took these quickly, and I think more foliage would be ideal. My basic goal is to get a shot with a dendro band and spring foliage in the background. Suggestions welcome.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/6355854/165552248-0ae99c77-1caa-4303-bbaa-2723beaf860e.png">

**Comment by ValentineHerr** [comment]
I like the bottom-right one. I think it looks more artistic. With nicer weather and more foliage that could look great. If you can get a picture early morning or evening, the lighting might be even better.

**Comment by teixeirak** [comment]
Thanks, @ValentineHerr ! You're also welcome to try taking some. 

Here's a few more that didn't fit in the first screenshot:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/6355854/165555584-65491efe-f8f0-43f8-bec6-0a88fe9f693c.png">

I'll hope for some good weather conditions next week. (I think the early morning or evening would be tough, though)

**Comment by ValentineHerr** [comment]
I went to the plot on Thursday. Here are some potential shots. Let me know what you think
![image](https://user-images.githubusercontent.com/19673377/166458053-3cc6a7b0-da99-44a2-a9a6-6dcffe46f7a7.png)

![image](https://user-images.githubusercontent.com/19673377/166457968-5da00619-5321-472f-8cc4-cb8cdcde8f97.png)

**Comment by teixeirak** [comment]
I like these! I think my favorites are  3922 and 3909, mainly because of lighting (foregrounds look very dark in some, but perhaps could be lightened). These inspired many of the ones I took. I'll post thumbnails and then work on sorting out some favorites. There are A LOT.

**Comment by teixeirak** [comment]
Here are thumbnails. The hearts indicate some of the best, but aren't very thorough and in some cases just indicate ones that Yannik liked. :-)

<img width="965" alt="image" src="https://user-images.githubusercontent.com/6355854/166822577-d246b48c-e34f-4e57-b791-b7a02e2c5a85.png">
<img width="974" alt="image" src="https://user-images.githubusercontent.com/6355854/166822684-fe504425-7c38-49c8-94e7-0fc12f3f89e2.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/6355854/166822753-734a3b9e-d125-4621-acbd-d9d8ba6e3efe.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/6355854/166822809-994c730a-1f04-4129-880e-ba136852cc86.png">

**Comment by teixeirak** [comment]
Bigger versions of some favorites. For most, there are multiple similar shots, and I can go back and make sure I have the best:

1.  
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6355854/166823117-9e5db06c-fc47-45f2-bc99-3cbe23bff96e.png">

2. 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6355854/166823216-628b05d2-b473-4be7-b7a3-ee75346d0fa0.png">

3. 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/6355854/166823300-64598903-2f25-4918-9bfb-9093831bc869.png">

4. I took this one including dead wood to convey the long residence time of wood in the ecosystem:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/6355854/166823464-a9754c0d-b1ca-43de-9b41-4357feb786e5.png">


5. tulip poplar
<img width="675" alt="image" src="https://user-images.githubusercontent.com/6355854/166823723-3e94c36e-c03c-4a01-8f57-921e1abd95cd.png">

6. 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6355854/166823780-972ac553-de6e-43ae-a9f6-740f17cdc482.png">

7. 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/6355854/166823902-bcc4eb94-2e07-4aa3-b25f-ff8b6946b3d5.png">

8. (it would be cool to have a ForestGEO tag on the cover of Nature!)
<img width="688" alt="image" src="https://user-images.githubusercontent.com/6355854/166824081-6849f714-dd72-491e-9b0b-1bacb9ee3272.png">

9. I liked this one because it has pawpaw and dogwood flowers, although they are rather subtle
<img width="697" alt="image" src="https://user-images.githubusercontent.com/6355854/166824161-b617a7ae-f2e5-4998-a579-5dbc7ab31962.png">

10. This one emphasizes the dendro band
<img width="690" alt="image" src="https://user-images.githubusercontent.com/6355854/166824337-d883e68b-9bc7-48eb-a19a-f70781487a78.png">

**Comment by teixeirak** [comment]
Okay, @camerondow35 , @ValentineHerr , @rudeboybert , @mcgregorian1 , @gonzalezeb  (coauthors on GitHub), have at it! Which do you like? We can select 6. Vote for your favorites.

**Comment by mcgregorian1** [comment]
These are the ones I like
- 8 because it shows the ForestGEO tag
- 10 or 7 because it emphasizes the dendroband
- 4 because imo this is most artistic in the sense that it captures the dead wood, the live dendroband, and it looks like a cover photo to me already!

**Comment by teixeirak** [comment]
From Neil:  I like the first two, the ones that include the hickory. All I can see as a cover photo, though.

**Comment by rudeboybert** [comment]
They all look good, so any differences are minimal. that being said I would
- Drop 2 band is too small
- Drop 5 band is out of focus
- Drop 6 the stem takes up too much of the image IMO

**Comment by gonzalezeb** [comment]
If we still have time to comment, I agree with Albert. # 2 is my favorite. I miss my plot.

**Comment by teixeirak** [comment]
1- Neil likes.
2- Neil likes. Erika's favorite. Bert thinks the band is too small.
3- Bert likes that spring is front and center.
4- Ian likes.  Bert would crop to make band more prominent. Yannik likes.
5- Band out of focus (but may have similar where it is focused). Yannik really dislikes.
6- Bert thinks stem takes up too much of image. 
7- Ian likes because it emphasizes dendro band. Yannik likes 
8 - Ian likes (because includes ForestGEO tag). Yannik doesn't like-- particularly the grey sky and blank space itself. Krista thinks exposure is bad/ image is flat.
9. Yannik likes (2nd / 3rd favorite)
10- Neil likes. Ian likes because it emphasizes dendro band. Yannik likes (2nd / 3rd favorite)
