### ISSUE TITLE
numbers of records removed

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#141]
@camerondow35 , here's a comment from R1:

"I appreciated the clarifications done concerning the data cleaning process. However, I didn’t find in the manuscript the quantity of data that have been removed at it stages. I believe it is worth mentioning it."

We mention these numbers for some removal categories, but not for the following:

*The raw dendrometer band data were screened before analysis to remove records or entire tree-years that were either unreliable or inappropriate for our analysis. First, we manually screened the data for three classes of errors. First, when a measurement was drastically different from previous and following measurements, it was assumed to be a human error and removed. Second, when measurements remained essentially unchanged for several readings, followed by a sudden jump then return to a normal growth pattern, this was assumed to be a case where the band was stuck on the tree bark and then released. In these cases, the full annual record for the tree was removed. Third, data points that deviated substantially from normal growth patterns, but for unknown causes, were removed. *

Do you have those numbers? If these are difficult to retrieve, we could compare counts of total band-years vs those that made it into the final analysis, and present just those total numbers.

**Comment by teixeirak** [comment]
@camerondow35 , this is the one thing we have left to address in order to finish the paper and response to reviews.

**Comment by teixeirak** [comment]
@camerondow35 , I made the following assumptions when filling in these numbers. Please verify and edit if needed:
- [ ] records in Extended Data Table 1 are the pre-cleaning records *but do not include 1998 for Harvard Forest*
- [ ] the numbers removed (paragraph starting line 319, and also 343) do not include 1998 for Harvard Forest

If either of these assumptions is incorrect, we'll need to make some edits to the methods section and response to reviews. You do not need to change Extended Data Table 1.

**Comment by teixeirak** [comment]
Our messages crossed. From Teams chat:
- 1998 at HF is not included in the numbers dropped
- EDT1 is post-cleaning numbers

I will fix accordingly.

**Comment by teixeirak** [comment]
@camerondow35 , I fixed these numbers and believe we can close this issue. Please verify that you agree with my changes and reopen in case there's any problem.

**Comment by camerondow35** [comment]
Need to check this

**Comment by camerondow35** [comment]
Was 7 off on final count. Should be fixed now

**Comment by teixeirak** [comment]
Thanks, @camerondow35 !
