### ISSUE TITLE
Please ensure that the text size in all figures is at least 5 pt Arial. 

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#143]

**Comment by teixeirak** [comment]
@camerondow35 , I'm opening a separate issue here because I suspect that not all figures meet this guideline (which would be why the editor listed it). 

It's tough to tell, and I haven't found a good, easy way to measure font size. But here's a screenshot comparing font sizes to EDF3 (which I think has the smallest fonts):

<img width="717" alt="image" src="https://user-images.githubusercontent.com/6355854/167478015-b4703192-0a63-4d7d-a0ab-7b91a1fa58dc.png">

This looks like <5 to me.

Note that I had to reduce the figure to 70% its original size to fit on the page with its caption.

Could you please increase the font size here?

**Comment by camerondow35** [comment]
Done in latest push
