### ISSUE TITLE
additional issues to fix

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#147]
I overlooked these before. Breaking this out from issue #136.

> I have attached a document listing specific issues related to your manuscript

The following need to be addressed, and an author response put in the pdf:
- [x] Please note that the measure of centre for the error bars needs to be defined in the legends of extended data figures 4, 5.
- [x] Please indicate the statistical test used for data analysis and where appropriate, please specify whether it was one-sided or two-sided and whether adjustments were made for multiple comparisons, in the legends of figure 3, extended data figures 6, 7, supplementary table 1. (deal with SI table 1 in issue #146 )
- [x] Please ensure that datasets deposited in public repositories are now publicly accessible, and that accession codes or DOI are provided in the "Data Availability" section. As long as these datasets are not public, we cannot proceed with the acceptance of your paper. For data that have been obtained from publicly available sources, please provide a URL and the specific data product name in the data availability statement. Data with a DOI should be further cited in the methods reference section. (issue #149 )

There is also this one that doesn't require an author response, but seems like something we may need to deal with:
- [ ] <img width="1185" alt="image" src="https://user-images.githubusercontent.com/6355854/169692079-9f0d51f4-0246-4fd3-b7f8-89e9aa892490.png">

**Comment by camerondow35** [comment]
> Please note that the measure of centre for the error bars needs to be defined in the legends of extended data figures 4, 5.

Albert and I decided: "The 95% credible intervals are represented by bands centered on the posterior mean for each year." solved this issue

**Comment by camerondow35** [comment]
> Please ensure that datasets deposited in public repositories are now publicly accessible, and that accession codes or DOI are provided in the "Data Availability" section. As long as these datasets are not public, we cannot proceed with the acceptance of your paper. For data that have been obtained from publicly available sources, please provide a URL and the specific data product name in the data availability statement. Data with a DOI should be further cited in the methods reference section.

They want the DOI for each of our chronologies? We can copy and paste from the chronology table?

**Comment by teixeirak** [comment]
> They want the DOI for each of our chronologies? We can copy and paste from the chronology table?

That seems excessive. I think what we have is fine, but we have to solve #149, and check that this requirement is met for all other data .

**Comment by teixeirak** [comment]
I'm going to call this done.
