### ISSUE TITLE
items from checklists

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#151]
@camerondow35 , here's a list of things for you to verify:

from nature-manuscript-checklist-research_Dow.pdf: 
- [x] <img width="431" alt="image" src="https://user-images.githubusercontent.com/6355854/169695784-7e3def2e-4e4a-432b-bbc7-6c6d256fb477.png">
- [x] <img width="468" alt="image" src="https://user-images.githubusercontent.com/6355854/169695798-3ee1bd94-3856-4774-9af9-0594471adb99.png">

**Comment by camerondow35** [comment]
> Text in an editable format

I don't understand. Does this mean the text in the R scripts to control axis labels, etc.? 

> Font and font size

Didn't we already handle these in an [earlier issue? ](https://github.com/EcoClimLab/growth_phenology/issues/143)

>300 ppi JPEG

they're all at least 300 ppi. Do we need to reduce the resolution to 300 ppi if they're currently greater than 300?

**Comment by teixeirak** [comment]
You're right that we handled most/all of this in an earlier issue-- just put this here for you to double check because I couldn't check them all off based on what I knew offhand. But will do so now. 

(I presume the requested file formats are editable using their software. I'm sure they don't want our scripts!)
