### ISSUE TITLE
organize tree ring data

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#152]
@camerondow35 , I have the original files but am realizing that the tree cores section of the repo is a bit of a mess. I'm trying to clean it up, but some of this will require your help. Here's a running list of tasks:
- [x] I moved the folders for each site into a ["chronologies" folder](https://github.com/EcoClimLab/growth_phenology/tree/master/Data/tree_rings/chronologies) (and created a separate folder for "raw data"). You'll need to modify the path in your code.
- [x] Three files appeared to be unnecessary: Sites_ENTlab_Cameron_Krista.xlsx (internal planning doc), TRW_coord.xlsx & TRW_coord2.xlsx (last modified at the same time, appeared to duplicate [locations.csv](https://github.com/EcoClimLab/growth_phenology/blob/master/Data/tree_rings/locations.csv). I moved these to the private repo: https://github.com/EcoClimLab/growth_phenology_private/tree/main/Data/tree%20rings. Confirm that this is okay, fix if needed.
- [x] What is [crns_long.csv](https://github.com/EcoClimLab/growth_phenology/blob/master/Data/tree_rings/chronologies/crns_long.csv)? Delete if unused.
- [x] What is [crnlist.txt](https://github.com/EcoClimLab/growth_phenology/blob/master/Data/tree_rings/chronologies/crnlist.txt)? Delete if unused.
- [x] organize SCBI raw data
- [x] double check that we have all chronologies in raw data. 

_Originally posted by @teixeirak in https://github.com/EcoClimLab/growth_phenology/issues/149#issuecomment-1143649356_

**Comment by teixeirak** [comment]
@camerondow35 , this is the last significant step before submission. I'm going to keep pushing forward as best as I can and get it done (today if possible). I'll keep a record of any uncertainties in the checklist above, and you can always fix anything that needs to be fixed, and then we update  the zenodo release. But help on this ASAP would be useful.

**Comment by camerondow35** [comment]
@teixeirak I have the afternoon off thanks to thunder storms. Will work my way down the list now.

**Comment by teixeirak** [comment]
Awesome! I'm working on it too, starting with the SCBI raw data task.

**Comment by camerondow35** [comment]
> What is [crns_long.csv](https://github.com/EcoClimLab/growth_phenology/blob/master/Data/tree_rings/chronologies/crns_long.csv)? Delete if unused

Used in tree core drought analysis - keep

**Comment by teixeirak** [comment]
@camerondow35 , checking that we have all the right files:
- we have 102 site folders in the chronologies folder (expect 108)
- we have 213 .rwl files in the raw data folder (expect 207)

**Comment by teixeirak** [comment]
> > What is [crns_long.csv](https://github.com/EcoClimLab/growth_phenology/blob/master/Data/tree_rings/chronologies/crns_long.csv)? Delete if unused
> 
> Used in tree core drought analysis - keep

Okay. Could you please make sure there's a brief explanation of all files in the readme files?

**Comment by camerondow35** [comment]
> double check that we have all chronologies in raw data. I don't see Harvard Forest. Are we missing some from Neil??

Looks like we don't have the .rwl's from hf (except FRAM), just the chronos.

**Comment by teixeirak** [comment]
> > double check that we have all chronologies in raw data. I don't see Harvard Forest. Are we missing some from Neil??
> 
> Looks like we don't have the .rwl's from hf (except FRAM), just the chronos.

Okay, I'll work on that. They may all be in the HF data archive and not needed here. Are we missing others? (And why do we have extra .rwl files?)

**Comment by camerondow35** [comment]
>Are we missing others? (And why do we have extra .rwl files?)

Chcking this out now.

**Comment by teixeirak** [comment]
Okay, I obtained the HF raw chronologies from the source cited in the chronology_table and loaded them here.

**Comment by camerondow35** [comment]
Im going through them 1 by 1 and trying to sort which we have/which we need. It's just taking a long time!

**Comment by camerondow35** [comment]
Looks like we're potentially missing raw data for Mohawk Trail St.Forest, MA QURU

**Comment by camerondow35** [comment]
> we have 102 site folders in the chronologies folder (expect 108)

some sites are nested within the same folder (ie, TN has several sites in one folder) but i believe theyre all there

**Comment by teixeirak** [comment]
I opened a separate issue for the raw data file we need to locate. I believe we can close this issue now, although there still may be some work with readme files (#153 )
