### ISSUE TITLE
provide images as vector artwork

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#157]
There are a few matters that need to be attended to in order for us to progress with the final acceptance of your manuscript. We would be grateful if you could address the below items in a timely manner.
 
1.       All panels in all figure aside from 1b for the print journal have been supplied as rasterised (“flattened”) – which means, essentially, as photographic images. However, the panels ideally should be supplied as vector or layered artwork – where lines, arrows, scale bars and text, etc. are all in an editable format and labels are on separate layers to images.
 
We want to be able to carry out edits to text, stroke widths, etc, to scale artwork as necessary, and to ensure that the figures are presented in Nature house style.
 
The best way to obtain vector artwork is to go back to the software from which the panels were originally produced, and to save the files as either a PDF, an EPS (encapsulated postscript) or an SVG (scalable vector graphics) file. In order to avoid a font corruption problem, please use only Arial or Helvetica fonts in your figures, and when saving please ensure you select the "embed fonts" option (not "outline fonts") where appropriate. Chose to retain all editing capabilities.
 
You may need to go back to the original software the panels were created in, if the problem doesn’t stem from when the figure was compiled, but from a stage before.
 
See our guide to authors for more details:  [Final guide to authors (nature.com)](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Fdocuments%2FFinal_guide_to_authors.pdf&data=05%7C01%7CTeixeiraK%40si.edu%7Cbe3dbef295494827163f08da5f409a87%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637927029916442852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5JWYUIMPGjvkkh3964ejmSclkDIntj9KkInIUemI59U%3D&reserved=0)
 
When resupplying your figures or sending any queries about figure format, please copy in [art@nature.com](mailto:art@nature.com), and address the e-mail to Claire Welsh.
 
Best regards,

Parlee Parab
SNTPS
Nature

**Comment by ValentineHerr** [comment]
I can probably help but i need to clone the repo, which may take a while...

I had helped Susan for her Nature submission and here is a bit of an email I had sent her after I figured it out.

>In the code, you need to remove your svg() statements before you plot the figure (so the figure will appear in your plotting device) and replace dev.off() by:
`dev.copy2pdf(file="Fig 1.pdf", useDingbats=FALSE, family="serif", width = 7.2, height = 8)`

**Comment by teixeirak** [comment]
We definitely need:
- [ ] [schematic_summary.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/schematic_summary.png), produced by [schematic_summary.Rmd](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/schematic_summary.Rmd)
- [ ] [DOYtiming_allyears.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/DOYtiming_allyears.png), produced using [DOYtiming_allyears.Rmd](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/DOYtiming_allyears.Rmd)
- [ ] [tree_rings_tmax.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_tmax.png), produced using (???) [tmax_quiltplot.Rmd](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tmax_quiltplot.Rmd) (???) and compiled in powerpoint: [tree_rings_figs_compiled.pptx](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_figs_compiled.pptx). 

TBD whether we need the extended data figures as well.

**Comment by camerondow35** [comment]
> [tree_rings_tmax.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_tmax.png), produced using (???) [tmax_quiltplot.Rmd](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tmax_quiltplot.Rmd) (???) and compiled in powerpoint: [tree_rings_figs_compiled.pptx](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_figs_compiled.pptx).

produced in https://github.com/EcoClimLab/growth_phenology/blob/master/RScripts/Create_final_quiltplot.R

**Comment by camerondow35** [comment]
For [tree_rings_tmax.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_tmax.png), I have the script set up to run the my.dccplot for tmax RP (lines 242-349), then tmax DP (lines 352-410), saved as png. We then use [tree_rings_figs_complied.ppxt](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_figs_compiled.pptx) to assemble the two quiltplots together and add some text/other changes.

**Comment by teixeirak** [comment]
> For [tree_rings_tmax.png](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_tmax.png), I have the script set up to run the my.dccplot for tmax RP (lines 242-349), then tmax DP (lines 352-410), saved as png. We then use [tree_rings_figs_complied.ppxt](https://github.com/EcoClimLab/growth_phenology/blob/master/doc/manuscript/tables_figures/tree_rings_figs_compiled.pptx) to assemble the two quiltplots together and add some text/other changes.

For that one, I think we should send them the editable image(s) plus the powerpoint file.
